use soroban_sdk::contracterror;

// XDR spec hard-limits contracterror enums to 50 variants.
#[contracterror]
#[derive(Copy, Clone, Debug, Eq, PartialEq, PartialOrd, Ord)]
#[repr(u32)]
pub enum Error {
    AlreadyInitialized = 1,
    NotInitialized = 2,
    Unauthorized = 3,
    InvalidScore = 4,
    InvalidConfidence = 5,
    ScoreNotFound = 6,
    ContractPaused = 7,
    NoPendingAdminTransfer = 8,
    EmptyBatch = 9,          // also used for ConsensusInputEmpty
    BatchTooLarge = 10,
    ArithmeticOverflow = 11,
    UpgradeAlreadyPending = 12,
    NoPendingUpgrade = 13,
    InsufficientSigners = 14,
    UnauthorizedSigner = 15,
    /// Used for service threshold, consensus config, hysteresis margin,
    /// escalation threshold, and jump threshold validation errors.
    InvalidThreshold = 16,
    ServiceSetFull = 17,
    SignerAlreadyInSet = 18,
    SignerNotInSet = 19,
    UpgradeNotReady = 20,
    InvalidUpgradeDelay = 21,
    InvalidStalenessWindow = 22,
    RateLimitExceeded = 23,
    InvalidCooldown = 24,
    InvalidTimestamp = 25,
    ServicePubkeyNotSet = 26,
    InvalidAttestation = 27,
    InvalidPubkeyLength = 28,
    InvalidHistoryDepth = 29,
    InvalidMinConfidence = 30,
    InvalidWithdrawalAmount = 31,
    WithdrawalInProgress = 32,
    PairPaused = 33,
    PausedPairIndexFull = 34,
    AdminSetFull = 35,
    AdminSignerNotInSet = 36,
    InsufficientAdminSigners = 37,
    CyclicDelegation = 38,
    DelegateNotFound = 39,
    HighRiskWallet = 40,
    InvalidDecayRate = 41,
    ScoreEmbargoed = 42,
    BelowScoreFloor = 43,
    InvalidScoreFloorPolicy = 44,
    InsufficientConsensus = 45,
    FeeTokenNotSet = 46,
    // ── Threshold signature aggregation ──────────────────────────────────────
    AggregatePubkeyNotSet = 47,
    InvalidThresholdSignature = 48,
    ThresholdSignerNotInSet = 49,
    InsufficientThresholdSigners = 50,
}
